# Generated by Django 4.2.15 on 2026-08-29 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_add_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='restaurant',
            new_name='restaurants_name_0080ba_idx',
            old_name='restaurants_name_idx',
        ),
    ]
