# Generated by Django 4.2.15 on 2026-08-29 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_add_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='menu',
            new_name='menus_menu_date_221ef7_idx',
            old_name='menus_date_idx',
        ),
        migrations.RenameIndex(
            model_name='menu',
            new_name='menus_menu_restaur_eeee9d_idx',
            old_name='menus_restaurant_date_idx',
        ),
    ]
