# Generated by Django 4.2.15 on 2026-08-29 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0002_add_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='vote',
            new_name='votes_vote_date_1f8711_idx',
            old_name='votes_date_idx',
        ),
        migrations.RenameIndex(
            model_name='vote',
            new_name='votes_vote_employe_949aed_idx',
            old_name='votes_employee_date_idx',
        ),
        migrations.RenameIndex(
            model_name='vote',
            new_name='votes_vote_menu_id_29be17_idx',
            old_name='votes_menu_date_idx',
        ),
    ]
